version: '3.8'

services:
  # 1. PostgreSQL + PostGIS
  postgres-db:
    image: postgis/postgis:16-3.4
    container_name: greencity-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - green-city-net

  # 2. Redis
  redis-cache:
    image: redis:7-alpine
    container_name: greencity-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - green-city-net

  # 3. Auth Service (Yeni Eklenen Mikroservisimiz)
  auth-service:
    build:
      context: ./services/auth-service
    container_name: greencity-auth
    restart: always
    environment:
      PORT: 3000
      JWT_SECRET: GreenCitySuperSecretKey2026!
    networks:
      - green-city-net

  # 4. Sensor Service (Yeni Eklenen Mikroservis)
  sensor-service:
    build:
      context: ./services/sensor-service
    container_name: greencity-sensor
    restart: always
    environment:
      PORT: 3001
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres-db
    networks:
      - green-city-net
  # 4. Nginx API Gateway
  api-gateway:
    image: nginx:alpine
    container_name: greencity-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - postgres-db
      - redis-cache
      - auth-service
    networks:
      - green-city-net

networks:
  green-city-net:
    driver: bridge

volumes:
  postgres_data: