server {
    listen 80;
    server_name localhost;

    # Gateway Health Check
    location / {
        return 200 '{"status":"GreenCity API Gateway Active", "system":"OK"}';
        add_header Content-Type application/json;
    }

    # Auth Service Rotalaması (/api/auth/... -> auth-service:3000/...)
    location /api/auth/ {
        proxy_pass http://auth-service:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # Sensor Service Rotalaması (/api/sensors/... -> sensor-service:3001/...)
    location /api/sensors/ {
        proxy_pass http://sensor-service:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}